### ISSUE TITLE
运行CenterPointDetection模块报错

### ISSUE THREAD

**Issue by bazingaFXY** [ApolloAuto/apollo#14589]
[cyber_launch_93540] INFO Launch file [/apollo/modules/perception/production/launch/perception.launch]
[cyber_launch_93540] INFO ========================================================================================================================
[cyber_launch_93540] INFO Load module [perception_lidar] library: [perception_lidar] [CYBER_DEFAULT] conf: [/apollo/modules/perception/production/dag/0zai_perception.dag] exception_handler: []
[cyber_launch_93540] INFO Start process [perception_lidar] successfully. pid: 93547
[cyber_launch_93540] INFO ------------------------------------------------------------------------------------------------------------------------
[perception_lidar]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[perception_lidar]  I0913 17:20:25.658668 93547 module_argument.cc:81] []command: mainboard -d /apollo/modules/perception/production/dag/0zai_perception.dag -p perception_lidar -s CYBER_DEFAULT 
[perception_lidar]  I0913 17:20:25.658897 93547 global_data.cc:153] []host ip: 192.168.40.138
[perception_lidar]  I0913 17:20:25.660737 93547 module_argument.cc:57] []binary_name_ is mainboard, process_group_ is perception_lidar, has 1 dag conf
[perception_lidar]  I0913 17:20:25.660746 93547 module_argument.cc:60] []dag_conf: /apollo/modules/perception/production/dag/0zai_perception.dag
[perception_lidar]  WARNING: Logging before InitGoogleLogging() is written to STDERR
[perception_lidar]  I0913 17:20:28.834199 93547 analysis_config.cc:1044] In CollectShapeInfo mode, we will disable optimizations and collect the shape information of all intermediate tensors in the compute graph and calculate the min_shape, max_shape and opt_shape.
[perception_lidar]  I0913 17:20:29.024607 93547 analysis_predictor.cc:854] TensorRT subgraph engine is enabled
[perception_lidar]  I0913 17:20:29.024653 93547 analysis_predictor.cc:958] ir_optim is turned off, no IR pass will be executed
[perception_lidar]  --- Running analysis [ir_graph_build_pass]
[perception_lidar]  --- Running analysis [ir_graph_clean_pass]
[perception_lidar]  --- Running analysis [ir_analysis_pass]
[perception_lidar]  --- Running analysis [ir_params_sync_among_devices_pass]
[perception_lidar]  I0913 17:20:29.066828 93547 ir_params_sync_among_devices_pass.cc:100] Sync params from CPU to GPU
[perception_lidar]  --- Running analysis [adjust_cudnn_workspace_size_pass]
[perception_lidar]  --- Running analysis [inference_op_replace_pass]
[perception_lidar]  --- Running analysis [ir_graph_to_program_pass]
[perception_lidar]  I0913 17:20:29.167169 93547 analysis_predictor.cc:1007] ======= optimize end =======
[perception_lidar]  I0913 17:20:29.172111 93547 naive_executor.cc:102] ---  skip [feed], feed -> data
[perception_lidar]  I0913 17:20:29.175051 93547 naive_executor.cc:102] ---  skip [_generated_var_4], fetch -> fetch
[perception_lidar]  I0913 17:20:29.175065 93547 naive_executor.cc:102] ---  skip [_generated_var_6], fetch -> fetch
[perception_lidar]  I0913 17:20:29.175068 93547 naive_executor.cc:102] ---  skip [_generated_var_5], fetch -> fetch
[perception_lidar]  W0913 17:20:54.233073 93565 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.1
[perception_lidar]  W0913 17:20:54.244465 93565 gpu_resources.cc:91] device: 0, cuDNN Version: 8.0.
[perception_lidar]  W0913 17:20:54.260990 93565 place.cc:147] The `paddle::PlaceType::kCPU/kGPU` is deprecated since version 2.3, and will be removed in version 2.4! Please use `Tensor::is_cpu()/is_gpu()` method to determine the type of place.
[perception_lidar]  W0913 17:20:54.261025 93565 place.cc:136] The `paddle::PlaceType::kCPU/kGPU` is deprecated since version 2.3, and will be removed in version 2.4! Please use `paddle::CPUPlace()/DefaultGPUPlace()` to represent the place type.
[perception_lidar]  W0913 17:20:54.261031 93565 tensor.cc:69] The Tensor(place, shape) constructor is deprecated since version 2.3, and will be removed in version 2.4! Please use `paddle::empty/full` method to create a new Tensor instead. Reason: A legal tensor cannot be constructed only based on the `place` and `shape`, and datatype, layout, etc. is also required.
[perception_lidar]  W0913 17:20:54.261066 93565 tensor.cc:164] Allocating memory through `mutable_data` method is deprecated since version 2.3, and `mutable_data` method will be removed in version 2.4! Please use `paddle::empty/full` method to create a new Tensor with allocated memory, and use data<T>() method to get the memory pointer of tensor instead. Reason: When calling `mutable_data` to allocate memory, the place, datatype, and data layout of tensor may be in an illegal state.
[perception_lidar]  W0913 17:20:54.498150 93565 tensor.cc:164] Allocating memory through `mutable_data` method is deprecated since version 2.3, and `mutable_data` method will be removed in version 2.4! Please use `paddle::empty/full` method to create a new Tensor with allocated memory, and use data<T>() method to get the memory pointer of tensor instead. Reason: When calling `mutable_data` to allocate memory, the place, datatype, and data layout of tensor may be in an illegal state.
[perception_lidar]  terminate called after throwing an instance of 'phi::enforce::EnforceNotMet'
[perception_lidar]    what():  
[perception_lidar]  
[perception_lidar]    Compile Traceback (most recent call last):
[perception_lidar]      File "tools/export.py", line 62, in <module>
[perception_lidar]        main(args)
[perception_lidar]      File "tools/export.py", line 57, in main
[perception_lidar]        model.export(args.save_dir)
[perception_lidar]      File "/centerpoint/two_three/Paddle3D/paddle3d/models/detection/centerpoint/centerpoint.py", line 176, in export
[perception_lidar]        paddle.jit.save(self, save_path)
[perception_lidar]      File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/jit.py", line 629, in wrapper
[perception_lidar]        func(layer, path, input_spec, **configs)
[perception_lidar]      File "<decorator-gen-106>", line 2, in save
[perception_lidar]        
[perception_lidar]      File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
[perception_lidar]        return wrapped_func(*args, **kwargs)
[perception_lidar]      File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
[perception_lidar]        return func(*args, **kwargs)
[perception_lidar]      File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/jit.py", line 857, in save
[perception_lidar]        inner_input_spec, with_hook=with_hook)
[perception_lidar]      File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 528, in concrete_program_specify_input_spec
[perception_lidar]        *desired_input_spec, with_hook=with_hook)
[perception_lidar]      File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
[perception_lidar]        concrete_program, partial_program_layer = self._program_cache[cache_key]
[perception_lidar]      File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
[perception_lidar]        self._caches[item_id] = self._build_once(item)
[perception_lidar]      File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 790, in _build_once
[perception_lidar]        **cache_key.kwargs)
[perception_lidar]      File "<decorator-gen-104>", line 2, in from_func_spec
[perception_lidar]        
[perception_lidar]      File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
[perception_lidar]        return wrapped_func(*args, **kwargs)
[perception_lidar]      File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
[perception_lidar]        return func(*args, **kwargs)
[perception_lidar]      File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 733, in from_func_spec
[perception_lidar]        outputs = static_func(*inputs)
[perception_lidar]      File "/centerpoint/two_three/Paddle3D/paddle3d/models/detection/centerpoint/centerpoint.py", line 90, in forward
[perception_lidar]        x = self.extract_feat(data)
[perception_lidar]      File "/centerpoint/two_three/Paddle3D/paddle3d/models/detection/centerpoint/centerpoint.py", line 78, in extract_feat
[perception_lidar]        x = self.backbone(x)
[perception_lidar]      File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
[perception_lidar]        return self._dygraph_call_func(*inputs, **kwargs)
[perception_lidar]      File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
[perception_lidar]        outputs = self.forward(*inputs, **kwargs)
[perception_lidar]      File "/tmp/tmp57itbya1.py", line 19, in forward
[perception_lidar]        for_loop_body_8, [x, i])
[perception_lidar]      File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 45, in convert_while_loop
[perception_lidar]        loop_vars = _run_py_while(cond, body, loop_vars)
[perception_lidar]      File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 59, in _run_py_while
[perception_lidar]        loop_vars = body(*loop_vars)
[perception_lidar]      File "/centerpoint/two_three/Paddle3D/paddle3d/models/backbones/second_backbone.py", line 113, in forward
[perception_lidar]        x = self.blocks[i](x)
[perception_lidar]      File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
[perception_lidar]        return self._dygraph_call_func(*inputs, **kwargs)
[perception_lidar]      File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
[perception_lidar]        outputs = self.forward(*inputs, **kwargs)
[perception_lidar]      File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/container.py", line 98, in forward
[perception_lidar]        input = layer(input)
[perception_lidar]      File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
[perception_lidar]        return self._dygraph_call_func(*inputs, **kwargs)
[perception_lidar]      File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
[perception_lidar]        outputs = self.forward(*inputs, **kwargs)
[perception_lidar]      File "/usr/local/lib/python3.7/dist-packages/paddle/nn/layer/activation.py", line 470, in forward
[perception_lidar]        return F.relu(x, self._name)
[perception_lidar]      File "/usr/local/lib/python3.7/dist-packages/paddle/nn/functional/activation.py", line 582, in relu
[perception_lidar]        helper.append_op(type='relu', inputs={'X': x}, outputs={'Out': out})
[perception_lidar]      File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layer_helper.py", line 44, in append_op
[perception_lidar]        return self.main_program.current_block().append_op(*args, **kwargs)
[perception_lidar]      File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 3621, in append_op
[perception_lidar]        attrs=kwargs.get("attrs", None))
[perception_lidar]      File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 2635, in __init__
[perception_lidar]        for frame in traceback.extract_stack():
[perception_lidar]  
[perception_lidar]  --------------------------------------
[perception_lidar]  C++ Traceback (most recent call last):
[perception_lidar]  --------------------------------------
[perception_lidar]  0   apollo::cyber::croutine::CRoutine::Run()
[perception_lidar]  1   std::function<void ()>::operator()() const
[perception_lidar] 1}>::_M_invoke(std::_Any_data const&)
[perception_lidar] 1}::operator()() const
[perception_lidar] 1}::operator()(std::shared_ptr<apollo::drivers::PointCloud> const&) const
[perception_lidar]  5   apollo::cyber::Component<apollo::drivers::PointCloud, apollo::cyber::NullType, apollo::cyber::NullType, apollo::cyber::NullType>::Process(std::shared_ptr<apollo::drivers::PointCloud> const&)
[perception_lidar]  6   apollo::perception::onboard::DetectionComponent::Proc(std::shared_ptr<apollo::drivers::PointCloud> const&)
[perception_lidar]  7   apollo::perception::onboard::DetectionComponent::InternalProc(std::shared_ptr<apollo::drivers::PointCloud const> const&, std::shared_ptr<apollo::perception::onboard::LidarFrameMessage> const&)
[perception_lidar]  8   apollo::perception::lidar::LidarObstacleDetection::Process(apollo::perception::lidar::LidarObstacleDetectionOptions const&, std::shared_ptr<apollo::drivers::PointCloud const> const&, apollo::perception::lidar::LidarFrame*)
[perception_lidar]  9   apollo::perception::lidar::LidarObstacleDetection::ProcessCommon(apollo::perception::lidar::LidarObstacleDetectionOptions const&, apollo::perception::lidar::LidarFrame*)
[perception_lidar]  10  apollo::perception::lidar::CenterPointDetection::Detect(apollo::perception::lidar::LidarDetectorOptions const&, apollo::perception::lidar::LidarFrame*)
[perception_lidar]  11  apollo::perception::lidar::CenterPointDetection::DoInference(std::vector<float, std::allocator<float> > const&, int, std::vector<float, std::allocator<float> >*, std::vector<long, std::allocator<long> >*, std::vector<float, std::allocator<float> >*)
[perception_lidar]  12  apollo::perception::lidar::CenterPointDetection::Run(paddle_infer::Predictor*, std::vector<int, std::allocator<int> > const&, std::vector<float, std::allocator<float> > const&, std::vector<float, std::allocator<float> >*, std::vector<long, std::allocator<long> >*, std::vector<float, std::allocator<float> >*)
[perception_lidar]  13  paddle::AnalysisPredictor::ZeroCopyRun()
[perception_lidar]  14  paddle::framework::NaiveExecutor::Run()
[perception_lidar]  15  paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, phi::Place const&)
[perception_lidar]  16  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, phi::Place const&) const
[perception_lidar]  17  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, phi::Place const&, paddle::framework::RuntimeContext*) const
[perception_lidar]  18  void phi::ReluKernel<float, phi::GPUContext>(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor*)
[perception_lidar]  19  float* phi::DeviceContext::Alloc<float>(phi::TensorBase*, unsigned long, bool) const
[perception_lidar]  20  phi::DenseTensor::AllocateFrom(phi::Allocator*, paddle::experimental::DataType, unsigned long)
[perception_lidar]  21  paddle::memory::allocation::Allocator::Allocate(unsigned long)
[perception_lidar]  22  paddle::memory::allocation::StatAllocator::AllocateImpl(unsigned long)
[perception_lidar]  23  paddle::memory::allocation::Allocator::Allocate(unsigned long)
[perception_lidar]  24  paddle::memory::allocation::RetryAllocator::AllocateImpl(unsigned long)
[perception_lidar]  25  paddle::memory::allocation::NaiveBestFitAllocator::AllocateImpl(unsigned long)
[perception_lidar]  26  paddle::memory::legacy::AllocVisitor::result_type paddle::platform::VisitPlace<paddle::memory::legacy::AllocVisitor>(phi::Place const&, paddle::memory::legacy::AllocVisitor const&)
[perception_lidar]  27  void* paddle::memory::legacy::Alloc<phi::GPUPlace>(phi::GPUPlace const&, unsigned long)
[perception_lidar]  28  paddle::memory::detail::BuddyAllocator::Alloc(unsigned long)
[perception_lidar]  29  paddle::memory::detail::BuddyAllocator::RefillPool(unsigned long)
[perception_lidar]  30  paddle::memory::detail::BuddyAllocator::DeviceAllocateSize(std::function<unsigned long ()>, std::function<unsigned long ()>, unsigned long)
[perception_lidar]  31  paddle::platform::GpuAvailableMemToAlloc()
[perception_lidar]  32  paddle::platform::GpuMemoryUsage(unsigned long*, unsigned long*)
[perception_lidar]  33  paddle::platform::RecordedGpuMemGetInfo(unsigned long*, unsigned long*, unsigned long*, unsigned long*, int)
[perception_lidar]  34  phi::enforce::EnforceNotMet::EnforceNotMet(phi::ErrorSummary const&, char const*, int)
[perception_lidar]  35  phi::enforce::GetCurrentTraceBackString[abi:cxx11](bool)
[perception_lidar]  
[perception_lidar]  ----------------------
[perception_lidar]  Error Message Summary:
[perception_lidar]  ----------------------
[perception_lidar]  ExternalError: CUDA error(209), no kernel image is available for execution on the device. 
[perception_lidar] group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /apollo/paddle_inference_workspace/Paddle/paddle/fluid/platform/device/gpu/gpu_info.cc:130)
[perception_lidar]    [operator < relu > error]
[cyber_launch_93540] ERROR Process [perception_lidar] has died [pid 93547, exit code -6, cmd mainboard -d /apollo/modules/perception/production/dag/0zai_perception.dag -p perception_lidar -s CYBER_DEFAULT].

**Comment by xxmiprai** [comment]
我也碰到了这个问题，可能与paddleinference有关，我用源码自己编译了paddleinference，可以解决。

**Comment by Skye-Jiang** [comment]
> 我也碰到了这个问题，可能与paddleinference有关，我用源码自己编译了paddleinference，可以解决。
你好，我也遇到这个问题，请问方便给出具体如何编译的吗？

**Comment by bazingaFXY** [comment]
下载替换了2.3.2的paddleinference，问题就解决了，https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/Tables.html#Compile
