### ISSUE TITLE
Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by liuyangly25** [ApolloAuto/apollo#5505]
Hello,

I am getting this cudnn error when running apollo lowcost visualizer(`./scripts/perception_offline_visualizer.sh`) on ubuntu 14.04.3. NVIDIA driver version is 375.39 for host and docker.  

Please help. Thanks.

error detial:

SCNN_D_27_SCNN_D_26/sum_0_split_1
I0824 11:03:26.985291 13256 net.cpp:144] Setting up SCNN_D_27_SCNN_D_26/sum_0_split
I0824 11:03:26.985327 13256 net.cpp:151] Top shape: 1 64 1 80 (5120)
I0824 11:03:26.985339 13256 net.cpp:151] Top shape: 1 64 1 80 (5120)
I0824 11:03:26.985344 13256 net.cpp:159] Memory required for data: 324034560
I0824 11:03:26.985352 13256 layer_factory.hpp:79] Creating layer SCNN_D_27
I0824 11:03:26.985368 13256 net.cpp:94] Creating Layer SCNN_D_27
I0824 11:03:26.985376 13256 net.cpp:428] SCNN_D_27 <- SCNN_D_27_SCNN_D_26/sum_0_split_0
I0824 11:03:26.985390 13256 net.cpp:402] SCNN_D_27 -> SCNN_D_27/message
I0824 11:03:26.990255 13256 net.cpp:144] Setting up SCNN_D_27
I0824 11:03:26.990289 13256 net.cpp:151] Top shape: 1 64 1 80 (5120)
I0824 11:03:26.990299 13256 net.cpp:159] Memory required for data: 324055040
I0824 11:03:26.990309 13256 net.cpp:487] Sharing parameters 'SCNN_D_w' owned by layer 'SCNN_D_1', param index 0
I0824 11:03:26.990317 13256 layer_factory.hpp:79] Creating layer SCNN_D_27/relu
I0824 11:03:26.990327 13256 net.cpp:94] Creating Layer SCNN_D_27/relu
I0824 11:03:26.990337 13256 net.cpp:428] SCNN_D_27/relu <- SCNN_D_27/message
I0824 11:03:26.990348 13256 net.cpp:389] SCNN_D_27/relu -> SCNN_D_27/message (in-place)
F0824 11:03:26.991583 13256 cudnn_relu_layer.cpp:13] Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR
*** Check failure stack trace: ***
[33m[ WARN] [1535079800.556615700]: transport file: /home/tmp/ros/etc/ros/transport_mode.yaml is not map[0m
[33m[ WARN] [1535079800.556783525]: Parse transport_mode file failed[0m

**Comment by freeHackOfJeff** [comment]
I would recommend you read https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_apollo_2.5_perception_visualizer.md again, and try that by following up those steps, and more details info is required for us to diagnosis.

**Comment by freeHackOfJeff** [comment]
I would recommend you read https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_run_apollo_2.5_perception_visualizer.md again, and try that by following up those steps, and more details info is required for us to diagnosis.

**Comment by lianglia-apollo** [comment]
We have updated to nvidia-docker. It should solve the driver version issue which lasts for quite a long time. Thanks for @wanglei828 !!!
Please let us know if you have more issues on drivers.

**Comment by liuyangly25** [comment]
Thank you,  @lianglia-apollo @weidezhang @freeHackOfJeff  I will do it from scratch again. Hope the cudnn issue is gone on my end.
